name: Run tests and checks

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: x64

    - name: Install dependencies
      run: python -m pip install tox

    - name: Run pre-commit tox job
      run: tox -e pre-commit

  test:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install dependencies
      run: python -m pip install codecov tox

    - name: Run ${{ matrix.python }} tox job
      run: tox -e py
